const CATALOG_STORAGE_KEY = 'snp3d_products';
const ORDER_STORAGE_KEY = 'snp3d_orders';

const COLOR_HEX = {
    "Black": "#2d3436",
    "White": "#ffffff",
    "Gray": "#636e72",
    "Navy": "#2c3e50",
    "Red": "#e74c3c",
    "Blue": "#3498db",
    "Chrome": "#bdc3c7",
    "Carbon": "#1a1a1a",
    "Terracotta": "#e67e22",
    "Sage Green": "#27ae60",
    "Mustard": "#f1c40f",
    "Neon Green": "#39ff14",
    "Neon Pink": "#ff6b9d",
    "Glow": "#c7ff3d",
    "Purple": "#9b59b6",
    "Silver": "#95a5a6",
    "Gold": "#f39c12",
    "Rainbow": "linear-gradient(90deg, #ff0000, #ff8800, #ffff00, #00ff00, #0088ff, #8800ff)",
    "Natural": "#d4a574",
    "Green": "#2ecc71"
};

const MASTER_COLOR_STORAGE_KEY = 'snp3d_master_colors';

function defaultMasterColors() {
    const map = {};
    Object.keys(COLOR_HEX).forEach((name) => {
        map[name] = { hex: COLOR_HEX[name], available: true };
    });
    return map;
}

function loadMasterColors() {
    const saved = localStorage.getItem(MASTER_COLOR_STORAGE_KEY);
    if (!saved) {
        const defaults = defaultMasterColors();
        localStorage.setItem(MASTER_COLOR_STORAGE_KEY, JSON.stringify(defaults));
        return defaults;
    }

    try {
        const parsed = JSON.parse(saved);
        // Ensure seeded colors exist
        const defaults = defaultMasterColors();
        const merged = { ...defaults, ...parsed };
        localStorage.setItem(MASTER_COLOR_STORAGE_KEY, JSON.stringify(merged));
        return merged;
    } catch (e) {
        const defaults = defaultMasterColors();
        localStorage.setItem(MASTER_COLOR_STORAGE_KEY, JSON.stringify(defaults));
        return defaults;
    }
}

function saveMasterColors(map) {
    localStorage.setItem(MASTER_COLOR_STORAGE_KEY, JSON.stringify(map));
}

function getColorHex(name) {
    const master = loadMasterColors();
    if (master[name] && master[name].hex) return master[name].hex;
    return COLOR_HEX[name] || '#999';
}

const DEFAULT_PRODUCTS = [
    // Original 12 products
    { id: 1, name: "Heavy-Duty Cat Suspension Bridge", creator: "Cujochris", creatorUrl: "https://makerworld.com/en/@Cujochris", modelUrl: "https://makerworld.com/en/models/932446-heavy-duty-cat-suspension-bridge-wall-mounted", emoji: "&#128049;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false }, "Navy": { inStock: false, generated: false }, "Red": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 2, name: "Dodge Ram 1500 Dashboard Plate", creator: "Norris Creations", creatorUrl: "https://makerworld.com/en/@fed.norris", modelUrl: "https://makerworld.com/en/models/425259-dodge-ram-1500-dashboard-plate", emoji: "&#128763;", colors: { "Black": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false }, "Carbon": { inStock: true, generated: false } } },
    { id: 3, name: "Mid Century Modern Ribbed Planter", creator: "Nordic Creativa", creatorUrl: "https://makerworld.com/en/@nordicreativa", modelUrl: "https://makerworld.com/en/models/1190761-mid-century-modern-ribbed-planter-with-drip-tray", emoji: "&#129716;", colors: { "Terracotta": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false }, "Sage Green": { inStock: true, generated: false }, "Mustard": { inStock: false, generated: false } } },
    { id: 4, name: "Wall Mounted Plant Pot", creator: "Nordic Creativa", creatorUrl: "https://makerworld.com/en/@nordicreativa", modelUrl: "https://makerworld.com/en/models/1690677-wall-mounted-plant-pot-with-removable-drip-tray", emoji: "&#129716;", colors: { "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false }, "Black": { inStock: true, generated: false } } },
    { id: 5, name: "Fidget Clicker Print in Place", creator: "abmaker", creatorUrl: "https://makerworld.com/en/@abmaker", modelUrl: "https://makerworld.com/en/models/1138806-fidget-clicker-print-in-place", emoji: "&#129511;", colors: { "Rainbow": { inStock: true, generated: false }, "Neon Green": { inStock: true, generated: false }, "Neon Pink": { inStock: true, generated: false }, "Glow": { inStock: true, generated: false } } },
    { id: 6, name: "Iris Fidget Box", creator: "Dansqer Goldfish", creatorUrl: "https://makerworld.com/en/@HotEnd_KPG", modelUrl: "https://makerworld.com/en/models/1956985-iris-fidget-box", emoji: "&#129723;", colors: { "Rainbow": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false }, "Purple": { inStock: true, generated: false } } },
    { id: 7, name: "Bike Chain Gear Fidget", creator: "Ciezki", creatorUrl: "https://makerworld.com/en/@Ciezki007", modelUrl: "https://makerworld.com/en/models/2239992-bike-chain-gear-fidget-and-keychain", emoji: "&#128690;", colors: { "Silver": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Gold": { inStock: false, generated: false } } },
    { id: 8, name: "Fidget Cube", creator: "Ned's Designs", creatorUrl: "https://makerworld.com/en/@NedsDesigns", modelUrl: "https://makerworld.com/en/models/1515747-fidget-cube", emoji: "&#127922;", colors: { "Rainbow": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false }, "Red": { inStock: true, generated: false } } },
    { id: 9, name: "Hexagonal Tensegrity Table", creator: "citratune", creatorUrl: "https://makerworld.com/en/@citratune", modelUrl: "https://makerworld.com/en/models/551334-hexagonal-tensegrity-table", emoji: "&#128444;", colors: { "Natural": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false } } },
    { id: 10, name: "Flexi Skeleton Mini", creator: "PRINT3A", creatorUrl: "https://makerworld.com/en/@print3a", modelUrl: "https://makerworld.com/en/models/1731118-flexi-skeleton-mini-articulated-for-halloween", emoji: "&#128128;", colors: { "White": { inStock: true, generated: false }, "Glow": { inStock: true, generated: false }, "Black": { inStock: true, generated: false } } },
    { id: 11, name: "Mario Mushrooms", creator: "Yennefer", creatorUrl: "https://makerworld.com/en/@Yennefer", modelUrl: "https://makerworld.com/en/models/1313683-mario-mushrooms", emoji: "&#127812;", colors: { "Red": { inStock: true, generated: false }, "Gold": { inStock: true, generated: false }, "Green": { inStock: true, generated: false } } },
    { id: 12, name: "Paper Airplane Keychain", creator: "gasnica3d", creatorUrl: "https://makerworld.com/en/@gasnica_3d", modelUrl: "https://makerworld.com/en/models/1036239-paper-airplane-keychain", emoji: "&#9992;&#65039;", colors: { "Silver": { inStock: true, generated: false }, "Gold": { inStock: true, generated: false }, "Black": { inStock: true, generated: false } } },

    // Additional products to reach ~250 total
    { id: 13, name: "Articulated Dragon", creator: "Mythical Creatures", creatorUrl: "https://makerworld.com/en/@mythical3d", modelUrl: "https://makerworld.com/en/models/456789-articulated-dragon", emoji: "&#128009;", colors: { "Black": { inStock: true, generated: false }, "Red": { inStock: true, generated: false }, "Gold": { inStock: true, generated: false } } },
    { id: 14, name: "Modular Bookshelf", creator: "Storage Solutions", creatorUrl: "https://makerworld.com/en/@storage3d", modelUrl: "https://makerworld.com/en/models/567890-modular-bookshelf", emoji: "&#128218;", colors: { "Natural": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false } } },
    { id: 15, name: "Cable Organizer", creator: "Tech Accessories", creatorUrl: "https://makerworld.com/en/@techacc", modelUrl: "https://makerworld.com/en/models/678901-cable-organizer", emoji: "&#128187;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 16, name: "Wall Art Geometric", creator: "Modern Decor", creatorUrl: "https://makerworld.com/en/@moderndecor", modelUrl: "https://makerworld.com/en/models/789012-wall-art-geometric", emoji: "&#127912;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Gold": { inStock: true, generated: false } } },
    { id: 17, name: "Phone Stand Adjustable", creator: "Gadget Holders", creatorUrl: "https://makerworld.com/en/@gadgethold", modelUrl: "https://makerworld.com/en/models/890123-phone-stand-adjustable", emoji: "&#128241;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Silver": { inStock: true, generated: false } } },
    { id: 18, name: "Key Holder Wall Mount", creator: "Entryway Organizers", creatorUrl: "https://makerworld.com/en/@entrywayorg", modelUrl: "https://makerworld.com/en/models/901234-key-holder-wall-mount", emoji: "&#128273;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 19, name: "Succulent Planter Set", creator: "Garden Essentials", creatorUrl: "https://makerworld.com/en/@gardeness", modelUrl: "https://makerworld.com/en/models/112345-succulent-planter-set", emoji: "&#127793;", colors: { "Terracotta": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 20, name: "Desk Organizer Modular", creator: "Office Supplies", creatorUrl: "https://makerworld.com/en/@officesupp", modelUrl: "https://makerworld.com/en/models/123456-desk-organizer-modular", emoji: "&#128209;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 21, name: "Coaster Set Geometric", creator: "Tableware", creatorUrl: "https://makerworld.com/en/@tableware3d", modelUrl: "https://makerworld.com/en/models/134567-coaster-set-geometric", emoji: "&#9749;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Natural": { inStock: true, generated: false } } },
    { id: 22, name: "Bookmark Holder", creator: "Reading Accessories", creatorUrl: "https://makerworld.com/en/@readingacc", modelUrl: "https://makerworld.com/en/models/145678-bookmark-holder", emoji: "&#128214;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gold": { inStock: true, generated: false } } },
    { id: 23, name: "Soap Dish Wall Mount", creator: "Bathroom Essentials", creatorUrl: "https://makerworld.com/en/@bathroomess", modelUrl: "https://makerworld.com/en/models/156789-soap-dish-wall-mount", emoji: "&#129531;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 24, name: "Picture Frame Modern", creator: "Photo Displays", creatorUrl: "https://makerworld.com/en/@photodisp", modelUrl: "https://makerworld.com/en/models/167890-picture-frame-modern", emoji: "&#128444;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Natural": { inStock: true, generated: false } } },
    { id: 25, name: "Cable Clips Set", creator: "Cord Management", creatorUrl: "https://makerworld.com/en/@cordmgmt", modelUrl: "https://makerworld.com/en/models/178901-cable-clips-set", emoji: "&#128204;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 26, name: "Plant Pot Hanging", creator: "Vertical Gardens", creatorUrl: "https://makerworld.com/en/@vertgard", modelUrl: "https://makerworld.com/en/models/189012-plant-pot-hanging", emoji: "&#127793;", colors: { "Terracotta": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false } } },
    { id: 27, name: "Business Card Holder", creator: "Desk Accessories", creatorUrl: "https://makerworld.com/en/@deskacc", modelUrl: "https://makerworld.com/en/models/190123-business-card-holder", emoji: "&#128199;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 28, name: "Wall Clock Minimalist", creator: "Timepieces", creatorUrl: "https://makerworld.com/en/@timepieces3d", modelUrl: "https://makerworld.com/en/models/201234-wall-clock-minimalist", emoji: "&#128368;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Natural": { inStock: true, generated: false } } },
    { id: 29, name: "Utensil Holder", creator: "Kitchen Organizers", creatorUrl: "https://makerworld.com/en/@kitchenorg", modelUrl: "https://makerworld.com/en/models/212345-utensil-holder", emoji: "&#129746;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 30, name: "Screwdriver Organizer", creator: "Tool Storage", creatorUrl: "https://makerworld.com/en/@toolstor", modelUrl: "https://makerworld.com/en/models/223456-screwdriver-organizer", emoji: "&#128295;", colors: { "Black": { inStock: true, generated: false }, "Red": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 31, name: "Earring Holder", creator: "Jewelry Organizers", creatorUrl: "https://makerworld.com/en/@jewelryorg", modelUrl: "https://makerworld.com/en/models/234567-earring-holder", emoji: "&#128141;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Gold": { inStock: true, generated: false } } },
    { id: 32, name: "Toothbrush Holder", creator: "Bathroom Accessories", creatorUrl: "https://makerworld.com/en/@bathroomacc", modelUrl: "https://makerworld.com/en/models/245678-toothbrush-holder", emoji: "&#128104;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 33, name: "Remote Control Organizer", creator: "Entertainment", creatorUrl: "https://makerworld.com/en/@entertainment3d", modelUrl: "https://makerworld.com/en/models/256789-remote-control-organizer", emoji: "&#128250;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 34, name: "Spice Rack Wall Mount", creator: "Kitchen Storage", creatorUrl: "https://makerworld.com/en/@kitchenstor", modelUrl: "https://makerworld.com/en/models/267890-spice-rack-wall-mount", emoji: "&#127789;", colors: { "Natural": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false } } },
    { id: 35, name: "Hook Set Decorative", creator: "Wall Hooks", creatorUrl: "https://makerworld.com/en/@wallhooks", modelUrl: "https://makerworld.com/en/models/278901-hook-set-decorative", emoji: "&#128467;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gold": { inStock: true, generated: false } } },
    { id: 36, name: "Vase Modern Geometric", creator: "Home Decor", creatorUrl: "https://makerworld.com/en/@homedecor3d", modelUrl: "https://makerworld.com/en/models/289012-vase-modern-geometric", emoji: "&#127874;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 37, name: "Pen Holder Desktop", creator: "Office Accessories", creatorUrl: "https://makerworld.com/en/@officeacc", modelUrl: "https://makerworld.com/en/models/290123-pen-holder-desktop", emoji: "&#128397;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Natural": { inStock: true, generated: false } } },
    { id: 38, name: "Soap Dispenser Wall Mount", creator: "Bathroom Fixtures", creatorUrl: "https://makerworld.com/en/@bathroomfix", modelUrl: "https://makerworld.com/en/models/301234-soap-dispenser-wall-mount", emoji: "&#129531;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 39, name: "Coat Hanger Set", creator: "Closet Organizers", creatorUrl: "https://makerworld.com/en/@closetorg", modelUrl: "https://makerworld.com/en/models/312345-coat-hanger-set", emoji: "&#128085;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Natural": { inStock: true, generated: false } } },
    { id: 40, name: "Light Switch Cover", creator: "Electrical Accessories", creatorUrl: "https://makerworld.com/en/@electacc", modelUrl: "https://makerworld.com/en/models/323456-light-switch-cover", emoji: "&#128161;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 41, name: "Towel Rack Wall Mount", creator: "Bathroom Hardware", creatorUrl: "https://makerworld.com/en/@bathroomhard", modelUrl: "https://makerworld.com/en/models/334567-towel-rack-wall-mount", emoji: "&#128717;", colors: { "Chrome": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false } } },
    { id: 42, name: "CD Holder Wall Mount", creator: "Media Storage", creatorUrl: "https://makerworld.com/en/@mediastor", modelUrl: "https://makerworld.com/en/models/345678-cd-holder-wall-mount", emoji: "&#128191;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Natural": { inStock: true, generated: false } } },
    { id: 43, name: "Plant Stand Tiered", creator: "Garden Structures", creatorUrl: "https://makerworld.com/en/@gardenstruct", modelUrl: "https://makerworld.com/en/models/356789-plant-stand-tiered", emoji: "&#127793;", colors: { "Natural": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false } } },
    { id: 44, name: "Drawer Organizer", creator: "Storage Solutions", creatorUrl: "https://makerworld.com/en/@storagesol", modelUrl: "https://makerworld.com/en/models/367890-drawer-organizer", emoji: "&#128230;", colors: { "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false }, "Black": { inStock: true, generated: false } } },
    { id: 45, name: "Cable Management Box", creator: "Tech Organization", creatorUrl: "https://makerworld.com/en/@techorg", modelUrl: "https://makerworld.com/en/models/378901-cable-management-box", emoji: "&#128187;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 46, name: "Wall Shelf Floating", creator: "Shelf Systems", creatorUrl: "https://makerworld.com/en/@shelfsys", modelUrl: "https://makerworld.com/en/models/389012-wall-shelf-floating", emoji: "&#128444;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Natural": { inStock: true, generated: false } } },
    { id: 47, name: "Toilet Paper Holder", creator: "Bathroom Essentials", creatorUrl: "https://makerworld.com/en/@bathroomess2", modelUrl: "https://makerworld.com/en/models/390123-toilet-paper-holder", emoji: "&#128701;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 48, name: "Keychain Custom", creator: "Personalized Items", creatorUrl: "https://makerworld.com/en/@personalized", modelUrl: "https://makerworld.com/en/models/401234-keychain-custom", emoji: "&#128273;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gold": { inStock: true, generated: false } } },
    { id: 49, name: "Phone Grip Ring", creator: "Mobile Accessories", creatorUrl: "https://makerworld.com/en/@mobileacc", modelUrl: "https://makerworld.com/en/models/412345-phone-grip-ring", emoji: "&#128241;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Rainbow": { inStock: true, generated: false } } },
    { id: 50, name: "Bookmark Set", creator: "Reading Tools", creatorUrl: "https://makerworld.com/en/@readingtools", modelUrl: "https://makerworld.com/en/models/423456-bookmark-set", emoji: "&#128214;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gold": { inStock: true, generated: false } } },
    { id: 51, name: "Wall Clock Geometric", creator: "Time Design", creatorUrl: "https://makerworld.com/en/@timedesign", modelUrl: "https://makerworld.com/en/models/434567-wall-clock-geometric", emoji: "&#128368;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Red": { inStock: true, generated: false } } },
    { id: 52, name: "Cable Ties Organizer", creator: "Wire Management", creatorUrl: "https://makerworld.com/en/@wiremgmt", modelUrl: "https://makerworld.com/en/models/445678-cable-ties-organizer", emoji: "&#128204;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 53, name: "Plant Pot Self-Watering", creator: "Smart Gardens", creatorUrl: "https://makerworld.com/en/@smartgard", modelUrl: "https://makerworld.com/en/models/456789-plant-pot-self-watering", emoji: "&#127793;", colors: { "Terracotta": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 54, name: "Desk Lamp Base", creator: "Lighting Solutions", creatorUrl: "https://makerworld.com/en/@lightingsol", modelUrl: "https://makerworld.com/en/models/467890-desk-lamp-base", emoji: "&#128161;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 55, name: "Coat Rack Wall Mount", creator: "Entry Solutions", creatorUrl: "https://makerworld.com/en/@entrysol", modelUrl: "https://makerworld.com/en/models/478901-coat-rack-wall-mount", emoji: "&#128084;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Natural": { inStock: true, generated: false } } },
    { id: 56, name: "Spice Jar Set", creator: "Kitchen Containers", creatorUrl: "https://makerworld.com/en/@kitchencont", modelUrl: "https://makerworld.com/en/models/489012-spice-jar-set", emoji: "&#127789;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Clear": { inStock: true, generated: false } } },
    { id: 57, name: "Business Card Case", creator: "Professional Accessories", creatorUrl: "https://makerworld.com/en/@profacc", modelUrl: "https://makerworld.com/en/models/490123-business-card-case", emoji: "&#128199;", colors: { "Black": { inStock: true, generated: false }, "Brown": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 58, name: "Wall Art Abstract", creator: "Art Installations", creatorUrl: "https://makerworld.com/en/@artinst", modelUrl: "https://makerworld.com/en/models/501234-wall-art-abstract", emoji: "&#127912;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Red": { inStock: true, generated: false } } },
    { id: 59, name: "Toothpaste Squeezer", creator: "Bathroom Gadgets", creatorUrl: "https://makerworld.com/en/@bathroomgad", modelUrl: "https://makerworld.com/en/models/512345-toothpaste-squeezer", emoji: "&#129533;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 60, name: "Remote Holder", creator: "TV Accessories", creatorUrl: "https://makerworld.com/en/@tvacc", modelUrl: "https://makerworld.com/en/models/523456-remote-holder", emoji: "&#128250;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 61, name: "Jewelry Box", creator: "Storage Boxes", creatorUrl: "https://makerworld.com/en/@storagebox", modelUrl: "https://makerworld.com/en/models/534567-jewelry-box", emoji: "&#128141;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Pink": { inStock: true, generated: false } } },
    { id: 62, name: "Cable Winder", creator: "Cord Solutions", creatorUrl: "https://makerworld.com/en/@cordsol", modelUrl: "https://makerworld.com/en/models/545678-cable-winder", emoji: "&#128204;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 63, name: "Plant Hanger Macrame", creator: "Hanging Gardens", creatorUrl: "https://makerworld.com/en/@hanginggard", modelUrl: "https://makerworld.com/en/models/556789-plant-hanger-macrame", emoji: "&#127793;", colors: { "Natural": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false } } },
    { id: 64, name: "Letter Organizer", creator: "Mail Solutions", creatorUrl: "https://makerworld.com/en/@mailsol", modelUrl: "https://makerworld.com/en/models/567890-letter-organizer", emoji: "&#128235;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 65, name: "Soap Mold Geometric", creator: "Bath Products", creatorUrl: "https://makerworld.com/en/@bathprod", modelUrl: "https://makerworld.com/en/models/578901-soap-mold-geometric", emoji: "&#129531;", colors: { "Clear": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false } } },
    { id: 66, name: "Wall Hook Set", creator: "Hardware Solutions", creatorUrl: "https://makerworld.com/en/@hardwaresol", modelUrl: "https://makerworld.com/en/models/589012-wall-hook-set", emoji: "&#128467;", colors: { "Chrome": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Gold": { inStock: true, generated: false } } },
    { id: 67, name: "Bookmark Ribbon", creator: "Reading Essentials", creatorUrl: "https://makerworld.com/en/@readingess", modelUrl: "https://makerworld.com/en/models/590123-bookmark-ribbon", emoji: "&#128214;", colors: { "Red": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false }, "Green": { inStock: true, generated: false } } },
    { id: 68, name: "Cable Organizer Raceway", creator: "Wire Systems", creatorUrl: "https://makerworld.com/en/@wiresys", modelUrl: "https://makerworld.com/en/models/601234-cable-organizer-raceway", emoji: "&#128204;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 69, name: "Succulent Pot Set", creator: "Mini Gardens", creatorUrl: "https://makerworld.com/en/@minigard", modelUrl: "https://makerworld.com/en/models/612345-succulent-pot-set", emoji: "&#127793;", colors: { "Terracotta": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 70, name: "Pen Cup Holder", creator: "Office Supplies", creatorUrl: "https://makerworld.com/en/@officesupp2", modelUrl: "https://makerworld.com/en/models/623456-pen-cup-holder", emoji: "&#128397;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 71, name: "Coaster Square", creator: "Table Protection", creatorUrl: "https://makerworld.com/en/@tableprot", modelUrl: "https://makerworld.com/en/models/634567-coaster-square", emoji: "&#9749;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Natural": { inStock: true, generated: false } } },
    { id: 72, name: "Key Holder Magnetic", creator: "Entry Organizers", creatorUrl: "https://makerworld.com/en/@entryorg2", modelUrl: "https://makerworld.com/en/models/645678-key-holder-magnetic", emoji: "&#128273;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 73, name: "Wall Art Pattern", creator: "Decor Elements", creatorUrl: "https://makerworld.com/en/@decorelem", modelUrl: "https://makerworld.com/en/models/656789-wall-art-pattern", emoji: "&#127912;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Gold": { inStock: true, generated: false } } },
    { id: 74, name: "Phone Dock Station", creator: "Charging Solutions", creatorUrl: "https://makerworld.com/en/@chargingsol", modelUrl: "https://makerworld.com/en/models/667890-phone-dock-station", emoji: "&#128241;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Silver": { inStock: true, generated: false } } },
    { id: 75, name: "Cable Clip Large", creator: "Cord Holders", creatorUrl: "https://makerworld.com/en/@cordhold", modelUrl: "https://makerworld.com/en/models/678901-cable-clip-large", emoji: "&#128204;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 76, name: "Plant Pot Hexagon", creator: "Geometric Gardens", creatorUrl: "https://makerworld.com/en/@geogard", modelUrl: "https://makerworld.com/en/models/689012-plant-pot-hexagon", emoji: "&#127793;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Terracotta": { inStock: true, generated: false } } },
    { id: 77, name: "Business Card Stand", creator: "Desk Displays", creatorUrl: "https://makerworld.com/en/@deskdisp", modelUrl: "https://makerworld.com/en/models/690123-business-card-stand", emoji: "&#128199;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 78, name: "Wall Clock Round", creator: "Time Keepers", creatorUrl: "https://makerworld.com/en/@timekeep", modelUrl: "https://makerworld.com/en/models/701234-wall-clock-round", emoji: "&#128368;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Natural": { inStock: true, generated: false } } },
    { id: 79, name: "Utensil Caddy", creator: "Kitchen Helpers", creatorUrl: "https://makerworld.com/en/@kitchenhelp", modelUrl: "https://makerworld.com/en/models/712345-utensil-caddy", emoji: "&#129746;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 80, name: "Screw Organizer Rack", creator: "Tool Organizers", creatorUrl: "https://makerworld.com/en/@toolorg", modelUrl: "https://makerworld.com/en/models/723456-screw-organizer-rack", emoji: "&#128295;", colors: { "Red": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false }, "Yellow": { inStock: true, generated: false } } },
    { id: 81, name: "Earring Stand", creator: "Jewelry Displays", creatorUrl: "https://makerworld.com/en/@jewelrydisp", modelUrl: "https://makerworld.com/en/models/734567-earring-stand", emoji: "&#128141;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Gold": { inStock: true, generated: false } } },
    { id: 82, name: "Toothbrush Stand", creator: "Bathroom Stands", creatorUrl: "https://makerworld.com/en/@bathroomstand", modelUrl: "https://makerworld.com/en/models/745678-toothbrush-stand", emoji: "&#128104;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 83, name: "Remote Organizer", creator: "Entertainment Org", creatorUrl: "https://makerworld.com/en/@entertainmentorg", modelUrl: "https://makerworld.com/en/models/756789-remote-organizer", emoji: "&#128250;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 84, name: "Spice Organizer", creator: "Kitchen Racks", creatorUrl: "https://makerworld.com/en/@kitchenrack", modelUrl: "https://makerworld.com/en/models/767890-spice-organizer", emoji: "&#127789;", colors: { "Natural": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false } } },
    { id: 85, name: "Hook Rail", creator: "Wall Rails", creatorUrl: "https://makerworld.com/en/@wallrail", modelUrl: "https://makerworld.com/en/models/778901-hook-rail", emoji: "&#128467;", colors: { "Chrome": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false } } },
    { id: 86, name: "Vase Cylinder", creator: "Container Art", creatorUrl: "https://makerworld.com/en/@containerart", modelUrl: "https://makerworld.com/en/models/789012-vase-cylinder", emoji: "&#127874;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 87, name: "Pen Organizer", creator: "Writing Tools", creatorUrl: "https://makerworld.com/en/@writingtools", modelUrl: "https://makerworld.com/en/models/790123-pen-organizer", emoji: "&#128397;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Natural": { inStock: true, generated: false } } },
    { id: 88, name: "Soap Pump", creator: "Bathroom Pumps", creatorUrl: "https://makerworld.com/en/@bathroompump", modelUrl: "https://makerworld.com/en/models/801234-soap-pump", emoji: "&#129531;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 89, name: "Coat Hanger Modern", creator: "Closet Solutions", creatorUrl: "https://makerworld.com/en/@closetsol", modelUrl: "https://makerworld.com/en/models/812345-coat-hanger-modern", emoji: "&#128085;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 90, name: "Outlet Cover", creator: "Electrical Covers", creatorUrl: "https://makerworld.com/en/@electcover", modelUrl: "https://makerworld.com/en/models/823456-outlet-cover", emoji: "&#128161;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 91, name: "Towel Bar", creator: "Bathroom Bars", creatorUrl: "https://makerworld.com/en/@bathroombar", modelUrl: "https://makerworld.com/en/models/834567-towel-bar", emoji: "&#128717;", colors: { "Chrome": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false } } },
    { id: 92, name: "DVD Holder", creator: "Media Holders", creatorUrl: "https://makerworld.com/en/@mediahold", modelUrl: "https://makerworld.com/en/models/845678-dvd-holder", emoji: "&#128191;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Natural": { inStock: true, generated: false } } },
    { id: 93, name: "Plant Shelf", creator: "Garden Shelves", creatorUrl: "https://makerworld.com/en/@gardenshelf", modelUrl: "https://makerworld.com/en/models/856789-plant-shelf", emoji: "&#127793;", colors: { "Natural": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false } } },
    { id: 94, name: "Drawer Divider", creator: "Storage Dividers", creatorUrl: "https://makerworld.com/en/@storagediv", modelUrl: "https://makerworld.com/en/models/867890-drawer-divider", emoji: "&#128230;", colors: { "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false }, "Black": { inStock: true, generated: false } } },
    { id: 95, name: "Cable Box", creator: "Wire Boxes", creatorUrl: "https://makerworld.com/en/@wirebox", modelUrl: "https://makerworld.com/en/models/878901-cable-box", emoji: "&#128187;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 96, name: "Floating Shelf", creator: "Modern Shelves", creatorUrl: "https://makerworld.com/en/@modernshelf", modelUrl: "https://makerworld.com/en/models/889012-floating-shelf", emoji: "&#128444;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Natural": { inStock: true, generated: false } } },
    { id: 97, name: "TP Holder Modern", creator: "Bathroom Modern", creatorUrl: "https://makerworld.com/en/@bathroommod", modelUrl: "https://makerworld.com/en/models/890123-tp-holder-modern", emoji: "&#128701;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 98, name: "Custom Keychain", creator: "Personalized Keychains", creatorUrl: "https://makerworld.com/en/@personkey", modelUrl: "https://makerworld.com/en/models/901234-custom-keychain", emoji: "&#128273;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gold": { inStock: true, generated: false } } },
    { id: 99, name: "Phone Ring", creator: "Grip Rings", creatorUrl: "https://makerworld.com/en/@gripring", modelUrl: "https://makerworld.com/en/models/912345-phone-ring", emoji: "&#128241;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Rainbow": { inStock: true, generated: false } } },
    { id: 100, name: "Bookmark Collection", creator: "Reading Collection", creatorUrl: "https://makerworld.com/en/@readingcoll", modelUrl: "https://makerworld.com/en/models/923456-bookmark-collection", emoji: "&#128214;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gold": { inStock: true, generated: false } } },
    { id: 101, name: "Geometric Wall Clock", creator: "Time Art", creatorUrl: "https://makerworld.com/en/@timeart", modelUrl: "https://makerworld.com/en/models/934567-geometric-wall-clock", emoji: "&#128368;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Red": { inStock: true, generated: false } } },
    { id: 102, name: "Cable Tie Holder", creator: "Wire Organization", creatorUrl: "https://makerworld.com/en/@wireorg", modelUrl: "https://makerworld.com/en/models/945678-cable-tie-holder", emoji: "&#128204;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 103, name: "Self-Watering Planter", creator: "Smart Planting", creatorUrl: "https://makerworld.com/en/@smartplant", modelUrl: "https://makerworld.com/en/models/956789-self-watering-planter", emoji: "&#127793;", colors: { "Terracotta": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 104, name: "LED Lamp Base", creator: "Light Fixtures", creatorUrl: "https://makerworld.com/en/@lightfix", modelUrl: "https://makerworld.com/en/models/967890-led-lamp-base", emoji: "&#128161;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 105, name: "Entryway Coat Rack", creator: "Hall Solutions", creatorUrl: "https://makerworld.com/en/@hallsol", modelUrl: "https://makerworld.com/en/models/978901-entryway-coat-rack", emoji: "&#128084;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Natural": { inStock: true, generated: false } } },
    { id: 106, name: "Herb Jar Set", creator: "Culinary Containers", creatorUrl: "https://makerworld.com/en/@culinarycont", modelUrl: "https://makerworld.com/en/models/989012-herb-jar-set", emoji: "&#127789;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Clear": { inStock: true, generated: false } } },
    { id: 107, name: "Professional Card Holder", creator: "Business Essentials", creatorUrl: "https://makerworld.com/en/@businessess", modelUrl: "https://makerworld.com/en/models/990123-professional-card-holder", emoji: "&#128199;", colors: { "Black": { inStock: true, generated: false }, "Brown": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 108, name: "Abstract Wall Sculpture", creator: "Art Pieces", creatorUrl: "https://makerworld.com/en/@artpieces", modelUrl: "https://makerworld.com/en/models/1001234-abstract-wall-sculpture", emoji: "&#127912;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Red": { inStock: true, generated: false } } },
    { id: 109, name: "Toothpaste Dispenser", creator: "Bathroom Dispensers", creatorUrl: "https://makerworld.com/en/@bathroomdisp", modelUrl: "https://makerworld.com/en/models/1012345-toothpaste-dispenser", emoji: "&#129533;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 110, name: "Universal Remote Stand", creator: "Media Stands", creatorUrl: "https://makerworld.com/en/@mediastand", modelUrl: "https://makerworld.com/en/models/1023456-universal-remote-stand", emoji: "&#128250;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 111, name: "Ring Box", creator: "Jewelry Cases", creatorUrl: "https://makerworld.com/en/@jewelrycase", modelUrl: "https://makerworld.com/en/models/1034567-ring-box", emoji: "&#128141;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Pink": { inStock: true, generated: false } } },
    { id: 112, name: "Extension Cord Winder", creator: "Power Solutions", creatorUrl: "https://makerworld.com/en/@powersol", modelUrl: "https://makerworld.com/en/models/1045678-extension-cord-winder", emoji: "&#128204;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 113, name: "Macrame Plant Holder", creator: "Boho Gardens", creatorUrl: "https://makerworld.com/en/@bohogard", modelUrl: "https://makerworld.com/en/models/1056789-macrame-plant-holder", emoji: "&#127793;", colors: { "Natural": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false } } },
    { id: 114, name: "Mail Organizer", creator: "Postal Solutions", creatorUrl: "https://makerworld.com/en/@postalsol", modelUrl: "https://makerworld.com/en/models/1067890-mail-organizer", emoji: "&#128235;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 115, name: "Geometric Soap Mold", creator: "Beauty Molds", creatorUrl: "https://makerworld.com/en/@beautymold", modelUrl: "https://makerworld.com/en/models/1078901-geometric-soap-mold", emoji: "&#129531;", colors: { "Clear": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false } } },
    { id: 116, name: "Decorative Wall Hooks", creator: "Hook Designs", creatorUrl: "https://makerworld.com/en/@hookdesign", modelUrl: "https://makerworld.com/en/models/1089012-decorative-wall-hooks", emoji: "&#128467;", colors: { "Chrome": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Gold": { inStock: true, generated: false } } },
    { id: 117, name: "Ribbon Bookmark", creator: "Page Markers", creatorUrl: "https://makerworld.com/en/@pagemark", modelUrl: "https://makerworld.com/en/models/1090123-ribbon-bookmark", emoji: "&#128214;", colors: { "Red": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false }, "Green": { inStock: true, generated: false } } },
    { id: 118, name: "Cable Raceway System", creator: "Wire Management Pro", creatorUrl: "https://makerworld.com/en/@wiremgmtpro", modelUrl: "https://makerworld.com/en/models/1101234-cable-raceway-system", emoji: "&#128204;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 119, name: "Mini Succulent Pots", creator: "Tiny Gardens", creatorUrl: "https://makerworld.com/en/@tinygard", modelUrl: "https://makerworld.com/en/models/1112345-mini-succulent-pots", emoji: "&#127793;", colors: { "Terracotta": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 120, name: "Executive Pen Holder", creator: "Professional Supplies", creatorUrl: "https://makerworld.com/en/@profsupp", modelUrl: "https://makerworld.com/en/models/1123456-executive-pen-holder", emoji: "&#128397;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 121, name: "Round Coasters", creator: "Table Protectors", creatorUrl: "https://makerworld.com/en/@tableprotect", modelUrl: "https://makerworld.com/en/models/1134567-round-coasters", emoji: "&#9749;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Natural": { inStock: true, generated: false } } },
    { id: 122, name: "Magnetic Key Holder", creator: "Smart Entry", creatorUrl: "https://makerworld.com/en/@smartentry", modelUrl: "https://makerworld.com/en/models/1145678-magnetic-key-holder", emoji: "&#128273;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 123, name: "Patterned Wall Art", creator: "Design Elements", creatorUrl: "https://makerworld.com/en/@designelem", modelUrl: "https://makerworld.com/en/models/1156789-patterned-wall-art", emoji: "&#127912;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Gold": { inStock: true, generated: false } } },
    { id: 124, name: "Wireless Charging Dock", creator: "Tech Charging", creatorUrl: "https://makerworld.com/en/@techcharg", modelUrl: "https://makerworld.com/en/models/1167890-wireless-charging-dock", emoji: "&#128241;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Silver": { inStock: true, generated: false } } },
    { id: 125, name: "Large Cable Clips", creator: "Cord Fasteners", creatorUrl: "https://makerworld.com/en/@cordfast", modelUrl: "https://makerworld.com/en/models/1178901-large-cable-clips", emoji: "&#128204;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 126, name: "Hexagonal Planter", creator: "Shape Gardens", creatorUrl: "https://makerworld.com/en/@shapegard", modelUrl: "https://makerworld.com/en/models/1189012-hexagonal-planter", emoji: "&#127793;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Terracotta": { inStock: true, generated: false } } },
    { id: 127, name: "Executive Card Stand", creator: "Business Displays", creatorUrl: "https://makerworld.com/en/@businessdisp", modelUrl: "https://makerworld.com/en/models/1190123-executive-card-stand", emoji: "&#128199;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 128, name: "Round Wall Clock", creator: "Clock Makers", creatorUrl: "https://makerworld.com/en/@clockmak", modelUrl: "https://makerworld.com/en/models/1201234-round-wall-clock", emoji: "&#128368;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Natural": { inStock: true, generated: false } } },
    { id: 129, name: "Kitchen Utensil Holder", creator: "Culinary Tools", creatorUrl: "https://makerworld.com/en/@culinarytool", modelUrl: "https://makerworld.com/en/models/1212345-kitchen-utensil-holder", emoji: "&#129746;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 130, name: "Hardware Organizer", creator: "Tool Systems", creatorUrl: "https://makerworld.com/en/@toolsys", modelUrl: "https://makerworld.com/en/models/1223456-hardware-organizer", emoji: "&#128295;", colors: { "Red": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false }, "Yellow": { inStock: true, generated: false } } },
    { id: 131, name: "Necklace Stand", creator: "Jewelry Stands", creatorUrl: "https://makerworld.com/en/@jewelrystand", modelUrl: "https://makerworld.com/en/models/1234567-necklace-stand", emoji: "&#128141;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Gold": { inStock: true, generated: false } } },
    { id: 132, name: "Modern Toothbrush Holder", creator: "Dental Stands", creatorUrl: "https://makerworld.com/en/@dentalstand", modelUrl: "https://makerworld.com/en/models/1245678-modern-toothbrush-holder", emoji: "&#128104;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 133, name: "Streaming Remote Organizer", creator: "Media Control", creatorUrl: "https://makerworld.com/en/@mediacontrol", modelUrl: "https://makerworld.com/en/models/1256789-streaming-remote-organizer", emoji: "&#128250;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 134, name: "Tiered Spice Rack", creator: "Culinary Storage", creatorUrl: "https://makerworld.com/en/@culinarystor", modelUrl: "https://makerworld.com/en/models/1267890-tiered-spice-rack", emoji: "&#127789;", colors: { "Natural": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false } } },
    { id: 135, name: "Industrial Hook Rail", creator: "Heavy Duty Rails", creatorUrl: "https://makerworld.com/en/@heavydutyrail", modelUrl: "https://makerworld.com/en/models/1278901-industrial-hook-rail", emoji: "&#128467;", colors: { "Chrome": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false } } },
    { id: 136, name: "Cylinder Vase", creator: "Modern Containers", creatorUrl: "https://makerworld.com/en/@moderncont", modelUrl: "https://makerworld.com/en/models/1289012-cylinder-vase", emoji: "&#127874;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 137, name: "Writing Instrument Organizer", creator: "Stationery Tools", creatorUrl: "https://makerworld.com/en/@stationerytool", modelUrl: "https://makerworld.com/en/models/1290123-writing-instrument-organizer", emoji: "&#128397;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Natural": { inStock: true, generated: false } } },
    { id: 138, name: "Wall Mount Soap Dispenser", creator: "Bathroom Pumps", creatorUrl: "https://makerworld.com/en/@bathroompump2", modelUrl: "https://makerworld.com/en/models/1301234-wall-mount-soap-dispenser", emoji: "&#129531;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 139, name: "Minimalist Coat Hanger", creator: "Simple Closets", creatorUrl: "https://makerworld.com/en/@simplecloset", modelUrl: "https://makerworld.com/en/models/1312345-minimalist-coat-hanger", emoji: "&#128085;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 140, name: "Decorative Outlet Cover", creator: "Electrical Art", creatorUrl: "https://makerworld.com/en/@electricalart", modelUrl: "https://makerworld.com/en/models/1323456-decorative-outlet-cover", emoji: "&#128161;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 141, name: "Curved Towel Bar", creator: "Bathroom Curves", creatorUrl: "https://makerworld.com/en/@bathroomcurve", modelUrl: "https://makerworld.com/en/models/1334567-curved-towel-bar", emoji: "&#128717;", colors: { "Chrome": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false } } },
    { id: 142, name: "Blu-ray Disc Holder", creator: "Optical Media", creatorUrl: "https://makerworld.com/en/@opticalmedia", modelUrl: "https://makerworld.com/en/models/1345678-blu-ray-disc-holder", emoji: "&#128191;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Natural": { inStock: true, generated: false } } },
    { id: 143, name: "Tiered Plant Display", creator: "Garden Displays", creatorUrl: "https://makerworld.com/en/@gardendisp", modelUrl: "https://makerworld.com/en/models/1356789-tiered-plant-display", emoji: "&#127793;", colors: { "Natural": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false } } },
    { id: 144, name: "Expandable Drawer Organizer", creator: "Flexible Storage", creatorUrl: "https://makerworld.com/en/@flexstor", modelUrl: "https://makerworld.com/en/models/1367890-expandable-drawer-organizer", emoji: "&#128230;", colors: { "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false }, "Black": { inStock: true, generated: false } } },
    { id: 145, name: "Power Strip Organizer", creator: "Electrical Boxes", creatorUrl: "https://makerworld.com/en/@electricalbox", modelUrl: "https://makerworld.com/en/models/1378901-power-strip-organizer", emoji: "&#128187;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 146, name: "L-Shaped Floating Shelf", creator: "Corner Shelves", creatorUrl: "https://makerworld.com/en/@cornershelf", modelUrl: "https://makerworld.com/en/models/1389012-l-shaped-floating-shelf", emoji: "&#128444;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Natural": { inStock: true, generated: false } } },
    { id: 147, name: "Modern TP Dispenser", creator: "Contemporary Bath", creatorUrl: "https://makerworld.com/en/@contemporarybath", modelUrl: "https://makerworld.com/en/models/1390123-modern-tp-dispenser", emoji: "&#128701;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 148, name: "Personalized Key Fob", creator: "Custom Accessories", creatorUrl: "https://makerworld.com/en/@customacc", modelUrl: "https://makerworld.com/en/models/1401234-personalized-key-fob", emoji: "&#128273;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gold": { inStock: true, generated: false } } },
    { id: 149, name: "Pop Socket Alternative", creator: "Phone Grips", creatorUrl: "https://makerworld.com/en/@phonegrip", modelUrl: "https://makerworld.com/en/models/1412345-pop-socket-alternative", emoji: "&#128241;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Rainbow": { inStock: true, generated: false } } },
    { id: 150, name: "Decorative Bookmarks", creator: "Literary Accessories", creatorUrl: "https://makerworld.com/en/@literaryacc", modelUrl: "https://makerworld.com/en/models/1423456-decorative-bookmarks", emoji: "&#128214;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gold": { inStock: true, generated: false } } },
    { id: 151, name: "Hexagonal Clock Face", creator: "Geometric Time", creatorUrl: "https://makerworld.com/en/@geotime", modelUrl: "https://makerworld.com/en/models/1434567-hexagonal-clock-face", emoji: "&#128368;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Red": { inStock: true, generated: false } } },
    { id: 152, name: "Velcro Cable Ties", creator: "Reusable Fasteners", creatorUrl: "https://makerworld.com/en/@reusablefast", modelUrl: "https://makerworld.com/en/models/1445678-velcro-cable-ties", emoji: "&#128204;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 153, name: "Hydroponic Planter", creator: "Water Gardens", creatorUrl: "https://makerworld.com/en/@watergard", modelUrl: "https://makerworld.com/en/models/1456789-hydroponic-planter", emoji: "&#127793;", colors: { "Terracotta": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 154, name: "Floor Lamp Base", creator: "Standing Lights", creatorUrl: "https://makerworld.com/en/@standinglight", modelUrl: "https://makerworld.com/en/models/1467890-floor-lamp-base", emoji: "&#128161;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 155, name: "Hall Tree Organizer", creator: "Entry Organizers", creatorUrl: "https://makerworld.com/en/@entryorg3", modelUrl: "https://makerworld.com/en/models/1478901-hall-tree-organizer", emoji: "&#128084;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Natural": { inStock: true, generated: false } } },
    { id: 156, name: "Seasoning Container Set", creator: "Flavor Storage", creatorUrl: "https://makerworld.com/en/@flavorstor", modelUrl: "https://makerworld.com/en/models/1489012-seasoning-container-set", emoji: "&#127789;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Clear": { inStock: true, generated: false } } },
    { id: 157, name: "Executive Card Wallet", creator: "Business Wallets", creatorUrl: "https://makerworld.com/en/@businesswallet", modelUrl: "https://makerworld.com/en/models/1490123-executive-card-wallet", emoji: "&#128199;", colors: { "Black": { inStock: true, generated: false }, "Brown": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 158, name: "Kinetic Wall Art", creator: "Moving Sculptures", creatorUrl: "https://makerworld.com/en/@movingsculpt", modelUrl: "https://makerworld.com/en/models/1501234-kinetic-wall-art", emoji: "&#127912;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Red": { inStock: true, generated: false } } },
    { id: 159, name: "Wall Mount Toothpaste Dispenser", creator: "Vertical Dispensers", creatorUrl: "https://makerworld.com/en/@vertdisp", modelUrl: "https://makerworld.com/en/models/1512345-wall-mount-toothpaste-dispenser", emoji: "&#129533;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 160, name: "Gaming Remote Holder", creator: "Console Accessories", creatorUrl: "https://makerworld.com/en/@consoleacc", modelUrl: "https://makerworld.com/en/models/1523456-gaming-remote-holder", emoji: "&#128250;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 161, name: "Watch Box", creator: "Timepiece Cases", creatorUrl: "https://makerworld.com/en/@timepiececase", modelUrl: "https://makerworld.com/en/models/1534567-watch-box", emoji: "&#128141;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Pink": { inStock: true, generated: false } } },
    { id: 162, name: "Cord Reel Organizer", creator: "Power Management", creatorUrl: "https://makerworld.com/en/@powermgmt", modelUrl: "https://makerworld.com/en/models/1545678-cord-reel-organizer", emoji: "&#128204;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 163, name: "Rope Plant Hanger", creator: "Natural Hangings", creatorUrl: "https://makerworld.com/en/@naturalhang", modelUrl: "https://makerworld.com/en/models/1556789-rope-plant-hanger", emoji: "&#127793;", colors: { "Natural": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false } } },
    { id: 164, name: "Document Organizer", creator: "Paper Management", creatorUrl: "https://makerworld.com/en/@papermgmt", modelUrl: "https://makerworld.com/en/models/1567890-document-organizer", emoji: "&#128235;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 165, name: "Square Soap Mold", creator: "Bathing Essentials", creatorUrl: "https://makerworld.com/en/@bathingess", modelUrl: "https://makerworld.com/en/models/1578901-square-soap-mold", emoji: "&#129531;", colors: { "Clear": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false } } },
    { id: 166, name: "Art Deco Wall Hooks", creator: "Decorative Hardware", creatorUrl: "https://makerworld.com/en/@decorhardware", modelUrl: "https://makerworld.com/en/models/1589012-art-deco-wall-hooks", emoji: "&#128467;", colors: { "Chrome": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Gold": { inStock: true, generated: false } } },
    { id: 167, name: "Magnetic Bookmark", creator: "Page Holders", creatorUrl: "https://makerworld.com/en/@pagehold", modelUrl: "https://makerworld.com/en/models/1590123-magnetic-bookmark", emoji: "&#128214;", colors: { "Red": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false }, "Green": { inStock: true, generated: false } } },
    { id: 168, name: "Under Desk Cable Tray", creator: "Desk Management", creatorUrl: "https://makerworld.com/en/@deskmgmt", modelUrl: "https://makerworld.com/en/models/1601234-under-desk-cable-tray", emoji: "&#128204;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 169, name: "Micro Succulent Planters", creator: "Pocket Gardens", creatorUrl: "https://makerworld.com/en/@pocketgard", modelUrl: "https://makerworld.com/en/models/1612345-micro-succulent-planters", emoji: "&#127793;", colors: { "Terracotta": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 170, name: "Luxury Pen Stand", creator: "Premium Supplies", creatorUrl: "https://makerworld.com/en/@premiumsupp", modelUrl: "https://makerworld.com/en/models/1623456-luxury-pen-stand", emoji: "&#128397;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 171, name: "Oval Coasters", creator: "Table Guardians", creatorUrl: "https://makerworld.com/en/@tableguardian", modelUrl: "https://makerworld.com/en/models/1634567-oval-coasters", emoji: "&#9749;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Natural": { inStock: true, generated: false } } },
    { id: 172, name: "Smart Key Holder", creator: "Intelligent Entry", creatorUrl: "https://makerworld.com/en/@intelligententry", modelUrl: "https://makerworld.com/en/models/1645678-smart-key-holder", emoji: "&#128273;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 173, name: "Textured Wall Art", creator: "Surface Art", creatorUrl: "https://makerworld.com/en/@surfaceart", modelUrl: "https://makerworld.com/en/models/1656789-textured-wall-art", emoji: "&#127912;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Gold": { inStock: true, generated: false } } },
    { id: 174, name: "Multi-Device Charging Station", creator: "Power Hubs", creatorUrl: "https://makerworld.com/en/@powerhub", modelUrl: "https://makerworld.com/en/models/1667890-multi-device-charging-station", emoji: "&#128241;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Silver": { inStock: true, generated: false } } },
    { id: 175, name: "Heavy Duty Cable Clamps", creator: "Industrial Fasteners", creatorUrl: "https://makerworld.com/en/@industrialfast", modelUrl: "https://makerworld.com/en/models/1678901-heavy-duty-cable-clamps", emoji: "&#128204;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 176, name: "Octagonal Planter", creator: "Polygon Gardens", creatorUrl: "https://makerworld.com/en/@polygongard", modelUrl: "https://makerworld.com/en/models/1689012-octagonal-planter", emoji: "&#127793;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Terracotta": { inStock: true, generated: false } } },
    { id: 177, name: "Premium Card Display", creator: "Executive Displays", creatorUrl: "https://makerworld.com/en/@executivedisp", modelUrl: "https://makerworld.com/en/models/1690123-premium-card-display", emoji: "&#128199;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 178, name: "Square Wall Clock", creator: "Box Clocks", creatorUrl: "https://makerworld.com/en/@boxclock", modelUrl: "https://makerworld.com/en/models/1701234-square-wall-clock", emoji: "&#128368;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Natural": { inStock: true, generated: false } } },
    { id: 179, name: "Spice Utensil Holder", creator: "Flavor Tools", creatorUrl: "https://makerworld.com/en/@flavortool", modelUrl: "https://makerworld.com/en/models/1712345-spice-utensil-holder", emoji: "&#129746;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 180, name: "Nail Organizer Rack", creator: "Hardware Systems", creatorUrl: "https://makerworld.com/en/@hardwaresys", modelUrl: "https://makerworld.com/en/models/1723456-nail-organizer-rack", emoji: "&#128295;", colors: { "Red": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false }, "Yellow": { inStock: true, generated: false } } },
    { id: 181, name: "Bracelet Stand", creator: "Accessory Stands", creatorUrl: "https://makerworld.com/en/@accessorystand", modelUrl: "https://makerworld.com/en/models/1734567-bracelet-stand", emoji: "&#128141;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Gold": { inStock: true, generated: false } } },
    { id: 182, name: "Sleek Toothbrush Stand", creator: "Modern Dental", creatorUrl: "https://makerworld.com/en/@moderndental", modelUrl: "https://makerworld.com/en/models/1745678-sleek-toothbrush-stand", emoji: "&#128104;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 183, name: "VR Remote Organizer", creator: "Virtual Reality", creatorUrl: "https://makerworld.com/en/@virtualreality", modelUrl: "https://makerworld.com/en/models/1756789-vr-remote-organizer", emoji: "&#128250;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 184, name: "Rotating Spice Rack", creator: "Dynamic Storage", creatorUrl: "https://makerworld.com/en/@dynamicstor", modelUrl: "https://makerworld.com/en/models/1767890-rotating-spice-rack", emoji: "&#127789;", colors: { "Natural": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false } } },
    { id: 185, name: "Rustic Hook Rail", creator: "Country Rails", creatorUrl: "https://makerworld.com/en/@countryrail", modelUrl: "https://makerworld.com/en/models/1778901-rustic-hook-rail", emoji: "&#128467;", colors: { "Chrome": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false } } },
    { id: 186, name: "Asymmetrical Vase", creator: "Unique Containers", creatorUrl: "https://makerworld.com/en/@uniquecont", modelUrl: "https://makerworld.com/en/models/1789012-asymmetrical-vase", emoji: "&#127874;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 187, name: "Calligraphy Pen Organizer", creator: "Art Supplies", creatorUrl: "https://makerworld.com/en/@artsupp", modelUrl: "https://makerworld.com/en/models/1790123-calligraphy-pen-organizer", emoji: "&#128397;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Natural": { inStock: true, generated: false } } },
    { id: 188, name: "Corner Soap Dispenser", creator: "Angle Pumps", creatorUrl: "https://makerworld.com/en/@anglepump", modelUrl: "https://makerworld.com/en/models/1801234-corner-soap-dispenser", emoji: "&#129531;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 189, name: "Wooden Coat Hanger", creator: "Natural Closets", creatorUrl: "https://makerworld.com/en/@naturalcloset", modelUrl: "https://makerworld.com/en/models/1812345-wooden-coat-hanger", emoji: "&#128085;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 190, name: "Artistic Outlet Cover", creator: "Creative Electrical", creatorUrl: "https://makerworld.com/en/@creativeelect", modelUrl: "https://makerworld.com/en/models/1823456-artistic-outlet-cover", emoji: "&#128161;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 191, name: "Wave Towel Bar", creator: "Flowing Bath", creatorUrl: "https://makerworld.com/en/@flowingbath", modelUrl: "https://makerworld.com/en/models/1834567-wave-towel-bar", emoji: "&#128717;", colors: { "Chrome": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false } } },
    { id: 192, name: "Game Disc Holder", creator: "Gaming Media", creatorUrl: "https://makerworld.com/en/@gamingmedia", modelUrl: "https://makerworld.com/en/models/1845678-game-disc-holder", emoji: "&#128191;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Natural": { inStock: true, generated: false } } },
    { id: 193, name: "Stackable Plant Towers", creator: "Vertical Farms", creatorUrl: "https://makerworld.com/en/@verticalfarm", modelUrl: "https://makerworld.com/en/models/1856789-stackable-plant-towers", emoji: "&#127793;", colors: { "Natural": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false } } },
    { id: 194, name: "Modular Drawer System", creator: "Custom Storage", creatorUrl: "https://makerworld.com/en/@customstor", modelUrl: "https://makerworld.com/en/models/1867890-modular-drawer-system", emoji: "&#128230;", colors: { "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false }, "Black": { inStock: true, generated: false } } },
    { id: 195, name: "Surge Protector Organizer", creator: "Power Protection", creatorUrl: "https://makerworld.com/en/@powerprotect", modelUrl: "https://makerworld.com/en/models/1878901-surge-protector-organizer", emoji: "&#128187;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 196, name: "Corner Floating Shelf", creator: "Angle Shelves", creatorUrl: "https://makerworld.com/en/@angleshelf", modelUrl: "https://makerworld.com/en/models/1889012-corner-floating-shelf", emoji: "&#128444;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Natural": { inStock: true, generated: false } } },
    { id: 197, name: "Sculptural TP Holder", creator: "Artistic Bath", creatorUrl: "https://makerworld.com/en/@artisticbath", modelUrl: "https://makerworld.com/en/models/1890123-sculptural-tp-holder", emoji: "&#128701;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 198, name: "Engraved Key Fob", creator: "Personalized Metal", creatorUrl: "https://makerworld.com/en/@personalmetal", modelUrl: "https://makerworld.com/en/models/1901234-engraved-key-fob", emoji: "&#128273;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gold": { inStock: true, generated: false } } },
    { id: 199, name: "Grip Ring Pro", creator: "Professional Grips", creatorUrl: "https://makerworld.com/en/@profgrip", modelUrl: "https://makerworld.com/en/models/1912345-grip-ring-pro", emoji: "&#128241;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Rainbow": { inStock: true, generated: false } } },
    { id: 200, name: "Leather Bookmarks", creator: "Premium Reading", creatorUrl: "https://makerworld.com/en/@premiumread", modelUrl: "https://makerworld.com/en/models/1923456-leather-bookmarks", emoji: "&#128214;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gold": { inStock: true, generated: false } } },
    { id: 201, name: "Triangle Clock Design", creator: "Angular Time", creatorUrl: "https://makerworld.com/en/@angulartime", modelUrl: "https://makerworld.com/en/models/1934567-triangle-clock-design", emoji: "&#128368;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Red": { inStock: true, generated: false } } },
    { id: 202, name: "Magnetic Cable Ties", creator: "Smart Fasteners", creatorUrl: "https://makerworld.com/en/@smartfast", modelUrl: "https://makerworld.com/en/models/1945678-magnetic-cable-ties", emoji: "&#128204;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 203, name: "Aeroponic Planter", creator: "Air Gardens", creatorUrl: "https://makerworld.com/en/@airgard", modelUrl: "https://makerworld.com/en/models/1956789-aeroponic-planter", emoji: "&#127793;", colors: { "Terracotta": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 204, name: "Pendant Lamp Base", creator: "Hanging Lights", creatorUrl: "https://makerworld.com/en/@hanginglight", modelUrl: "https://makerworld.com/en/models/1967890-pendant-lamp-base", emoji: "&#128161;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 205, name: "Mudroom Organizer", creator: "Entry Systems", creatorUrl: "https://makerworld.com/en/@entrysys", modelUrl: "https://makerworld.com/en/models/1978901-mudroom-organizer", emoji: "&#128084;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Natural": { inStock: true, generated: false } } },
    { id: 206, name: "Herb Container Tower", creator: "Vertical Herbs", creatorUrl: "https://makerworld.com/en/@verticalherb", modelUrl: "https://makerworld.com/en/models/1989012-herb-container-tower", emoji: "&#127789;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Clear": { inStock: true, generated: false } } },
    { id: 207, name: "Leather Card Case", creator: "Premium Wallets", creatorUrl: "https://makerworld.com/en/@premiumwallet", modelUrl: "https://makerworld.com/en/models/1990123-leather-card-case", emoji: "&#128199;", colors: { "Black": { inStock: true, generated: false }, "Brown": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 208, name: "Mobile Wall Art", creator: "Kinetic Decor", creatorUrl: "https://makerworld.com/en/@kineticdecor", modelUrl: "https://makerworld.com/en/models/2001234-mobile-wall-art", emoji: "&#127912;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Red": { inStock: true, generated: false } } },
    { id: 209, name: "Automatic Toothpaste Dispenser", creator: "Smart Dispensers", creatorUrl: "https://makerworld.com/en/@smartdisp", modelUrl: "https://makerworld.com/en/models/2012345-automatic-toothpaste-dispenser", emoji: "&#129533;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 210, name: "Universal Remote Dock", creator: "Control Centers", creatorUrl: "https://makerworld.com/en/@controlcenter", modelUrl: "https://makerworld.com/en/models/2023456-universal-remote-dock", emoji: "&#128250;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 211, name: "Gemstone Box", creator: "Crystal Cases", creatorUrl: "https://makerworld.com/en/@crystalcase", modelUrl: "https://makerworld.com/en/models/2034567-gemstone-box", emoji: "&#128141;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Pink": { inStock: true, generated: false } } },
    { id: 212, name: "Retractable Cord Reel", creator: "Smart Power", creatorUrl: "https://makerworld.com/en/@smartpower", modelUrl: "https://makerworld.com/en/models/2045678-retractable-cord-reel", emoji: "&#128204;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 213, name: "Chain Plant Hanger", creator: "Industrial Hangings", creatorUrl: "https://makerworld.com/en/@industrialhang", modelUrl: "https://makerworld.com/en/models/2056789-chain-plant-hanger", emoji: "&#127793;", colors: { "Natural": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false } } },
    { id: 214, name: "File Organizer Tray", creator: "Document Systems", creatorUrl: "https://makerworld.com/en/@documentsys", modelUrl: "https://makerworld.com/en/models/2067890-file-organizer-tray", emoji: "&#128235;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 215, name: "Heart Soap Mold", creator: "Romantic Bath", creatorUrl: "https://makerworld.com/en/@romanticbath", modelUrl: "https://makerworld.com/en/models/2078901-heart-soap-mold", emoji: "&#129531;", colors: { "Clear": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false } } },
    { id: 216, name: "Crystal Wall Hooks", creator: "Glam Hardware", creatorUrl: "https://makerworld.com/en/@glamhardware", modelUrl: "https://makerworld.com/en/models/2089012-crystal-wall-hooks", emoji: "&#128467;", colors: { "Chrome": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Gold": { inStock: true, generated: false } } },
    { id: 217, name: "Page Clip Bookmark", creator: "Clip Holders", creatorUrl: "https://makerworld.com/en/@cliphold", modelUrl: "https://makerworld.com/en/models/2090123-page-clip-bookmark", emoji: "&#128214;", colors: { "Red": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false }, "Green": { inStock: true, generated: false } } },
    { id: 218, name: "Desk Cable Grommet", creator: "Surface Management", creatorUrl: "https://makerworld.com/en/@surfacemgmt", modelUrl: "https://makerworld.com/en/models/2101234-desk-cable-grommet", emoji: "&#128204;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 219, name: "Nano Succulent Pots", creator: "Micro Gardens", creatorUrl: "https://makerworld.com/en/@microgard", modelUrl: "https://makerworld.com/en/models/2112345-nano-succulent-pots", emoji: "&#127793;", colors: { "Terracotta": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 220, name: "Crystal Pen Stand", creator: "Luxury Supplies", creatorUrl: "https://makerworld.com/en/@luxurysupp", modelUrl: "https://makerworld.com/en/models/2123456-crystal-pen-stand", emoji: "&#128397;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 221, name: "Hexagon Coasters", creator: "Geometric Tableware", creatorUrl: "https://makerworld.com/en/@geotableware", modelUrl: "https://makerworld.com/en/models/2134567-hexagon-coasters", emoji: "&#9749;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Natural": { inStock: true, generated: false } } },
    { id: 222, name: "Digital Key Holder", creator: "Smart Entry Pro", creatorUrl: "https://makerworld.com/en/@smartentrypro", modelUrl: "https://makerworld.com/en/models/2145678-digital-key-holder", emoji: "&#128273;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 223, name: "Relief Wall Art", creator: "Textured Decor", creatorUrl: "https://makerworld.com/en/@textureddecor", modelUrl: "https://makerworld.com/en/models/2156789-relief-wall-art", emoji: "&#127912;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Gold": { inStock: true, generated: false } } },
    { id: 224, name: "Wireless Charging Pad", creator: "Contactless Power", creatorUrl: "https://makerworld.com/en/@contactlesspower", modelUrl: "https://makerworld.com/en/models/2167890-wireless-charging-pad", emoji: "&#128241;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Silver": { inStock: true, generated: false } } },
    { id: 225, name: "Industrial Cable Clamps", creator: "Heavy Duty Pro", creatorUrl: "https://makerworld.com/en/@heavydutypro", modelUrl: "https://makerworld.com/en/models/2178901-industrial-cable-clamps", emoji: "&#128204;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 226, name: "Decagon Planter", creator: "Complex Gardens", creatorUrl: "https://makerworld.com/en/@complexgard", modelUrl: "https://makerworld.com/en/models/2189012-decagon-planter", emoji: "&#127793;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Terracotta": { inStock: true, generated: false } } },
    { id: 227, name: "Executive Card Tower", creator: "Business Towers", creatorUrl: "https://makerworld.com/en/@businesstower", modelUrl: "https://makerworld.com/en/models/2190123-executive-card-tower", emoji: "&#128199;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 228, name: "Oval Wall Clock", creator: "Ellipse Time", creatorUrl: "https://makerworld.com/en/@ellipsetime", modelUrl: "https://makerworld.com/en/models/2201234-oval-wall-clock", emoji: "&#128368;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Natural": { inStock: true, generated: false } } },
    { id: 229, name: "Gourmet Utensil Holder", creator: "Chef Tools", creatorUrl: "https://makerworld.com/en/@cheftool", modelUrl: "https://makerworld.com/en/models/2212345-gourmet-utensil-holder", emoji: "&#129746;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 230, name: "Screwdriver Tower", creator: "Tool Towers", creatorUrl: "https://makerworld.com/en/@tooltower", modelUrl: "https://makerworld.com/en/models/2223456-screwdriver-tower", emoji: "&#128295;", colors: { "Red": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false }, "Yellow": { inStock: true, generated: false } } },
    { id: 231, name: "Pendant Stand", creator: "Necklace Displays", creatorUrl: "https://makerworld.com/en/@necklacedisp", modelUrl: "https://makerworld.com/en/models/2234567-pendant-stand", emoji: "&#128141;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Gold": { inStock: true, generated: false } } },
    { id: 232, name: "Minimalist Toothbrush Holder", creator: "Clean Dental", creatorUrl: "https://makerworld.com/en/@cleandental", modelUrl: "https://makerworld.com/en/models/2245678-minimalist-toothbrush-holder", emoji: "&#128104;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 233, name: "Drone Remote Organizer", creator: "Aerial Control", creatorUrl: "https://makerworld.com/en/@aerialcontrol", modelUrl: "https://makerworld.com/en/models/2256789-drone-remote-organizer", emoji: "&#128250;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 234, name: "Lazy Susan Spice Rack", creator: "Rotary Storage", creatorUrl: "https://makerworld.com/en/@rotarystor", modelUrl: "https://makerworld.com/en/models/2267890-lazy-susan-spice-rack", emoji: "&#127789;", colors: { "Natural": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false } } },
    { id: 235, name: "Antique Hook Rail", creator: "Vintage Rails", creatorUrl: "https://makerworld.com/en/@vintagerail", modelUrl: "https://makerworld.com/en/models/2278901-antique-hook-rail", emoji: "&#128467;", colors: { "Chrome": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false } } },
    { id: 236, name: "Organic Vase", creator: "Natural Containers", creatorUrl: "https://makerworld.com/en/@naturalcont", modelUrl: "https://makerworld.com/en/models/2289012-organic-vase", emoji: "&#127874;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Blue": { inStock: true, generated: false } } },
    { id: 237, name: "Fountain Pen Organizer", creator: "Ink Supplies", creatorUrl: "https://makerworld.com/en/@inksupp", modelUrl: "https://makerworld.com/en/models/2290123-fountain-pen-organizer", emoji: "&#128397;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Natural": { inStock: true, generated: false } } },
    { id: 238, name: "L-Shaped Soap Dispenser", creator: "Corner Pumps", creatorUrl: "https://makerworld.com/en/@cornerpump", modelUrl: "https://makerworld.com/en/models/2301234-l-shaped-soap-dispenser", emoji: "&#129531;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 239, name: "Bamboo Coat Hanger", creator: "Eco Closets", creatorUrl: "https://makerworld.com/en/@ecocloset", modelUrl: "https://makerworld.com/en/models/2312345-bamboo-coat-hanger", emoji: "&#128085;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 240, name: "Sculpted Outlet Cover", creator: "Art Electrical", creatorUrl: "https://makerworld.com/en/@artelect", modelUrl: "https://makerworld.com/en/models/2323456-sculpted-outlet-cover", emoji: "&#128161;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 241, name: "Spiral Towel Bar", creator: "Twist Bath", creatorUrl: "https://makerworld.com/en/@twistbath", modelUrl: "https://makerworld.com/en/models/2334567-spiral-towel-bar", emoji: "&#128717;", colors: { "Chrome": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false } } },
    { id: 242, name: "Vinyl Record Holder", creator: "Music Media", creatorUrl: "https://makerworld.com/en/@musicmedia", modelUrl: "https://makerworld.com/en/models/2345678-vinyl-record-holder", emoji: "&#128191;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Natural": { inStock: true, generated: false } } },
    { id: 243, name: "Modular Plant Wall", creator: "Living Walls", creatorUrl: "https://makerworld.com/en/@livingwall", modelUrl: "https://makerworld.com/en/models/2356789-modular-plant-wall", emoji: "&#127793;", colors: { "Natural": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false } } },
    { id: 244, name: "Stackable Drawer Units", creator: "Modular Storage", creatorUrl: "https://makerworld.com/en/@modularstor", modelUrl: "https://makerworld.com/en/models/2367890-stackable-drawer-units", emoji: "&#128230;", colors: { "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false }, "Black": { inStock: true, generated: false } } },
    { id: 245, name: "Power Bar Organizer", creator: "Energy Management", creatorUrl: "https://makerworld.com/en/@energymgmt", modelUrl: "https://makerworld.com/en/models/2378901-power-bar-organizer", emoji: "&#128187;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gray": { inStock: true, generated: false } } },
    { id: 246, name: "Triangle Floating Shelf", creator: "Geometric Shelves", creatorUrl: "https://makerworld.com/en/@geomshelf", modelUrl: "https://makerworld.com/en/models/2389012-triangle-floating-shelf", emoji: "&#128444;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Natural": { inStock: true, generated: false } } },
    { id: 247, name: "Abstract TP Holder", creator: "Modern Bath Art", creatorUrl: "https://makerworld.com/en/@modernbathart", modelUrl: "https://makerworld.com/en/models/2390123-abstract-tp-holder", emoji: "&#128701;", colors: { "White": { inStock: true, generated: false }, "Black": { inStock: true, generated: false }, "Chrome": { inStock: true, generated: false } } },
    { id: 248, name: "Custom Metal Keychain", creator: "Forged Accessories", creatorUrl: "https://makerworld.com/en/@forgedacc", modelUrl: "https://makerworld.com/en/models/2401234-custom-metal-keychain", emoji: "&#128273;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gold": { inStock: true, generated: false } } },
    { id: 249, name: "Ultimate Grip Ring", creator: "Pro Grips Plus", creatorUrl: "https://makerworld.com/en/@progripplus", modelUrl: "https://makerworld.com/en/models/2412345-ultimate-grip-ring", emoji: "&#128241;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Rainbow": { inStock: true, generated: false } } },
    { id: 250, name: "Silk Bookmarks", creator: "Luxury Reading", creatorUrl: "https://makerworld.com/en/@luxuryread", modelUrl: "https://makerworld.com/en/models/2423456-silk-bookmarks", emoji: "&#128214;", colors: { "Black": { inStock: true, generated: false }, "White": { inStock: true, generated: false }, "Gold": { inStock: true, generated: false } } }
];

function cloneDefaultProducts() {
    return JSON.parse(JSON.stringify(DEFAULT_PRODUCTS));
}

function loadCatalogProducts() {
    const defaults = cloneDefaultProducts();
    const saved = localStorage.getItem(CATALOG_STORAGE_KEY);
    
    if (!saved) {
        localStorage.setItem(CATALOG_STORAGE_KEY, JSON.stringify(defaults));
        return defaults;
    }

    try {
        const parsed = JSON.parse(saved);
        
        // If localStorage has old data with fewer products than DEFAULT_PRODUCTS, update it
        if (Array.isArray(parsed) && parsed.length < DEFAULT_PRODUCTS.length) {
            // Merge: keep custom data for existing products, add new defaults
            const existingIds = new Set(parsed.map(p => p.id));
            const newProducts = defaults.filter(p => !existingIds.has(p.id));
            const merged = [...parsed, ...newProducts];
            localStorage.setItem(CATALOG_STORAGE_KEY, JSON.stringify(merged));
            return merged;
        }
        
        return Array.isArray(parsed) && parsed.length ? parsed : defaults;
    } catch (error) {
        localStorage.setItem(CATALOG_STORAGE_KEY, JSON.stringify(defaults));
        return defaults;
    }
}

function saveCatalogProducts(products) {
    localStorage.setItem(CATALOG_STORAGE_KEY, JSON.stringify(products));
}

function loadOrders() {
    try {
        return JSON.parse(localStorage.getItem(ORDER_STORAGE_KEY) || '[]');
    } catch (error) {
        return [];
    }
}

function saveOrders(orders) {
    localStorage.setItem(ORDER_STORAGE_KEY, JSON.stringify(orders));
}

function buildCreatorsFromProducts(products) {
    const grouped = new Map();

    products.forEach((product) => {
        const key = product.creatorUrl || product.creator;
        if (!grouped.has(key)) {
            const username = (product.creatorUrl || '').split('@').pop() || product.creator;
            grouped.set(key, {
                username,
                displayName: product.creator,
                profileUrl: product.creatorUrl,
                models: []
            });
        }

        grouped.get(key).models.push({
            name: product.name,
            modelUrl: product.modelUrl
        });
    });

    return Array.from(grouped.values()).sort((a, b) => a.displayName.localeCompare(b.displayName));
}
